[program:mutation_cascade]
command=/opt/supervisor-scripts/mutation-cascade.sh
autostart=true
autorestart=unexpected
startsecs=2
stopasgroup=true
killasgroup=true
environment=PROC_NAME="%(program_name)s"
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
