[program:tailscaled-unit05]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/tailscaled-unit05.sh
autostart=true
autorestart=unexpected
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
