from .minimax_h3_latent_upscaler_3d import (
    NODE_CLASS_MAPPINGS as OLD_3D_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as OLD_3D_NAMES,
)
from .H3_latent_upscaler_3d_v3 import (
    NODE_CLASS_MAPPINGS as V3_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as V3_NAMES,
)

NODE_CLASS_MAPPINGS = {**OLD_3D_CLASSES, **V3_CLASSES}
NODE_DISPLAY_NAME_MAPPINGS = {**OLD_3D_NAMES, **V3_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
